kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-persistent-storage
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data01"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: spring-boot-mongo-docker
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        run: spring-boot-mongo-docker
    spec: 
      containers: 
        - image: yangdu5/repository711
          name: spring-boot-mongo-docker
          ports: 
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-mongo-docker
  labels:
      run: spring-boot-mongo-docker
spec:
  ports:
    - port: 31000
      targetPort: 8080
  selector:
    run: spring-boot-mongo-docker
  type: NodePort

