apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: mongo
    app: demo
spec:
  containers:
    - name: mongo
      image: mongo:latest
      resources:
        requests:
          memory: "32Mi"
          cpu: "250m"
        limits:
          memory: "96Mi"
          cpu: "300m"
      ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017